CREATE DATABASE IF NOT EXISTS webrtc_proj DEFAULT CHARACTER SET UTF8;
USE webrtc_proj;

CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(32) NOT NULL,
    pw VARCHAR(32) NOT NULL,
    PRIMARY KEY (id)
);